./" Manpage for ai
.TH man 1 "3 February 2024" "1.0" "ai man page"
.SH NAME
ai - chat with ChatGPT-3
.SH SYNOPSIS
ai [your message]
.SH DESCRIPTION
with ai scipt you can chat with ChatGPT-3 for free
.SH OPTIONS
ai does not take any options
.SH BUGS
No known bugs.
.SH AUTHOR
mostafa vahedinezhad (mostafavn.ir | https://github.com/mostafa-vn)
.SH REPORTING BUGS
https://github.com/mostafa-vn/ai/issues